### ISSUE TITLE
Publishing is broken

### ISSUE THREAD

**Issue by SUPERCILEX** [yshrsmz/LicenseAdapter#39]
It looks like the `v2.0` version that was published on bintray is broken: https://dl.bintray.com/yshrsmz/maven/net/yslibrary/licenseadapter/licenseadapter/2.0.0/. There's only the `aar` file which isn't enough... I think updating [this dep](https://github.com/yshrsmz/LicenseAdapter/blob/14d189b367949b1088ff2cc56aa38ed32d8b2774/build.gradle#L16) to `0.8.0` might fix it, but I don't have access to bintray so I'm not sure. Running a `publishToMavenLocal` generates all the necessary files so it's just an uploading issue.

Sorry for possibly breaking your publishing! 😊

**Comment by SUPERCILEX** [comment]
Huh, well that's unfortunate. It could be that the plugin just isn't working right or something. I know this is the official one: https://github.com/bintray/gradle-bintray-plugin. And I just recently saw a similar issue: https://github.com/googlesamples/easypermissions/pull/188. Hopefully that helped a little! 😄

**Comment by yshrsmz** [comment]
looks like I did it!
just published v2.0.2

I ended up executing some more tasks as stated here https://github.com/novoda/bintray-release/issues/90#issuecomment-312427426

**Comment by SUPERCILEX** [comment]
Awesome!!! 😄
