### ISSUE TITLE
This library causes a gradle error

### ISSUE THREAD

**Issue by nuhkoca** [yshrsmz/LicenseAdapter#42]
Hi developer!

I want to use this library but when I implement it, I always getting **'All com.android.support libraries must use the exact same version specification'** and **'com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex'** errors.

Can you please tell me how do I fix this issue? Thanks!

**Comment by yshrsmz** [comment]
hi!
we should update support libs, but for now you have two options:

- use [resolution strategy](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#custom_dep_resolutions)
- explicitly specify all support library dependency in your `dependencies` block
