### ISSUE TITLE
When expanding the last two licenses, the second license appears above the header, and cannot be unexpanded.

### ISSUE THREAD

**Issue by pivotal-steve-chepurny** [yshrsmz/LicenseAdapter#7]
We were able to reproduce this every time with the following two licenses used:

 dataset.add(Licenses.fromGitHub("jakewharton/timber", Licenses.FILE_TXT));
 dataset.add(Licenses.fromGitHub("jakewharton/butterknife", Licenses.FILE_TXT));

This was found on 1.2.1 and 1.2.2

**Comment by yshrsmz** [comment]
Thanks for reporting!
just confirmed the behavior, will looking into it

**Comment by yshrsmz** [comment]
this was fixed(https://github.com/yshrsmz/LicenseAdapter/commit/df69719917a98fdeae3e92ccd35fe2876dad7dca) and released as v1.2.3. will be available soon
